name: Build in Ubuntu

on:
  push:
    branches:
    - 'master'
    tags:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  build:
    name: ${{ matrix.os }} build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            build-essential \
            cmake
    - name: Build
      run: |
        cmake -Bbuild -S.
        cmake --build build -j`nproc --all`
